# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='usr_register',
            fields=[
                ('uname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=10)),
                ('datt', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='library',
        ),
    ]
