# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_auto_20170621_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='collage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clg_name', models.CharField(max_length=200)),
                ('type_of_event', models.CharField(max_length=100)),
                ('event1', models.CharField(max_length=100)),
                ('event2', models.CharField(max_length=100)),
                ('event3', models.CharField(max_length=100)),
                ('event4', models.CharField(max_length=100)),
                ('event5', models.CharField(max_length=100)),
                ('event6', models.CharField(max_length=100)),
                ('event7', models.CharField(max_length=100)),
                ('event8', models.CharField(max_length=100)),
                ('event9', models.CharField(max_length=100)),
                ('event10', models.CharField(max_length=100)),
                ('event11', models.CharField(max_length=100)),
                ('event12', models.CharField(max_length=100)),
                ('event13', models.CharField(max_length=100)),
                ('event14', models.CharField(max_length=100)),
                ('event15', models.CharField(max_length=100)),
                ('Adress', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
            ],
        ),
    ]
