# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_collage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collage',
            name='event11',
        ),
        migrations.RemoveField(
            model_name='collage',
            name='event12',
        ),
        migrations.RemoveField(
            model_name='collage',
            name='event13',
        ),
        migrations.RemoveField(
            model_name='collage',
            name='event14',
        ),
        migrations.RemoveField(
            model_name='collage',
            name='event15',
        ),
        migrations.AlterField(
            model_name='collage',
            name='event10',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collage',
            name='event7',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collage',
            name='event8',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collage',
            name='event9',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
