# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_auto_20170626_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collage',
            name='event10',
        ),
        migrations.RemoveField(
            model_name='collage',
            name='event7',
        ),
        migrations.RemoveField(
            model_name='collage',
            name='event8',
        ),
        migrations.RemoveField(
            model_name='collage',
            name='event9',
        ),
        migrations.AlterField(
            model_name='collage',
            name='event3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collage',
            name='event4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collage',
            name='event5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collage',
            name='event6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
