# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_blog1'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog1',
            name='dat',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
