# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_blog1_dat'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog1',
            name='like',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
