# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0010_blog1_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog1',
            name='like',
        ),
    ]
