# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0011_remove_blog1_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog1',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
