# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0014_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog1',
            name='author',
        ),
    ]
