# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0017_blog1_user1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
        migrations.DeleteModel(
            name='usr_register',
        ),
    ]
