# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0019_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog1',
            name='title',
        ),
    ]
