# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 08:59
from __future__ import unicode_literals

import app2.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0022_auto_20170711_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog1',
            name='reply',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        #migrations.AlterField(
           # model_name='blog1',
            #name='image',
            #field=models.ImageField(blank=True, upload_to='user_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), app2.models.blog1.validate_size]),
        #),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='user_images'),
        ),
    ]
