# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0025_replytocomment_dat1'),
    ]

    operations = [
        migrations.AddField(
            model_name='replytocomment',
            name='replyblog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app2.blog1'),
        ),
    ]
