# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0026_replytocomment_replyblog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog1',
            name='reply',
        ),
    ]
