# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0027_remove_blog1_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog1',
            name='helpful',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='blog1',
            name='not_helpful',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
