# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0029_auto_20170718_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog1',
            name='notification',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
