# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 11:56
from __future__ import unicode_literals

import app2.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0032_auto_20170721_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog1',
            name='slug',
            field=models.SlugField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='user_images', validators=[app2.models.profile.validate_size]),
        ),
    ]
