# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0033_auto_20170729_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog1',
            name='helpful',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
