# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0035_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reciver',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
