# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0038_auto_20170806_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notblog',
        ),
        migrations.AddField(
            model_name='notification',
            name='to_user',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
