# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0040_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='collage',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
