# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0041_auto_20170806_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='school',
        ),
    ]
