# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0042_remove_profile_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='to_friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app2.profile'),
        ),
    ]
