# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0043_auto_20170807_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='to_friend',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
