# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0046_auto_20170810_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replytocomment',
            name='reply',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
