# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 11:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app2', '0047_auto_20170811_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='shared',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat2', models.DateTimeField(auto_now=True)),
                ('for_blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_blog', to='app2.blog1')),
                ('s_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s_user', to=settings.AUTH_USER_MODEL)),
                ('to_frnd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_frnd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
