# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0048_shared'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shared',
            name='for_blog',
        ),
        migrations.AddField(
            model_name='shared',
            name='s_comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
