# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0049_auto_20170812_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog1',
            name='like',
            field=models.NullBooleanField(),
        ),
    ]
