# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0050_blog1_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog1',
            name='like',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
