# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0053_auto_20170902_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog1',
            name='like_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='blog1',
            name='like',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
