# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0055_auto_20170902_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog1',
            name='like_user',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
