# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 14:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app2', '0056_auto_20170902_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='forlike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.CharField(blank=True, max_length=10)),
                ('dat5', models.DateTimeField(auto_now=True)),
                ('like_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to=settings.AUTH_USER_MODEL)),
                ('to_like', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog1',
            name='like',
        ),
        migrations.RemoveField(
            model_name='blog1',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='blog1',
            name='like_user',
        ),
    ]
