# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0057_auto_20170902_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog1',
            name='withblog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app2.forlike'),
        ),
    ]
