# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0058_blog1_withblog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog1',
            name='withblog',
        ),
        migrations.AddField(
            model_name='forlike',
            name='withblog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app2.blog1'),
        ),
    ]
