# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0059_auto_20170903_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forlike',
            name='withblog',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
