# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-24 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0061_blog1_like_acc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='user_images'),
        ),
    ]
